# .github/workflows/hello-world-template.yml
name: Hello World Template

on:
  workflow_call:  # This allows the workflow to be called from another workflow

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Say Hello
        run: echo "Hello, World from reusable workflow!"
